### ISSUE TITLE
有用户反应「泡面吧」在 Win 下显示为宋体比较难看

### ISSUE THREAD

**Issue by JasinYip** [haoranyu/Paomianba#3]
考虑补充一下微软雅黑之类的？

**Comment by haoranyu** [comment]
新版默认字体应该依次是：
兰亭黑、XX兰亭黑、微软雅黑、黑体，如果我记得没有错的话。

**Comment by haoranyu** [comment]
旧版本不会在单独做出更新。

**Comment by JasinYip** [comment]
我指的是新版的页面，那些 h2 好像只有一个 OpenSans-Semibold

**Comment by haoranyu** [comment]
把那个字体定义去掉吧？直接用全局定义的字体？

**Comment by JasinYip** [comment]
嗯……泡面吧这个需要你去看一下哈，我只是反映一下~~
